import { z } from 'zod';

// Zod schema for validating ObjectId
const objectIdSchema = z
  .string()
  .regex(/^[0-9a-fA-F]{24}$/, 'Invalid ObjectId format!');

// Zod schema for validating IOrder
export const orderZodSchema = z.object({
  email: z.string().email('Invalid email format!'),
  car: objectIdSchema, // Validates ObjectId reference
  quantity: z.number().min(1, 'Quantity must be at least 1!'),
  totalPrice: z.number().min(0, 'Total price cannot be negative!'),
  createdAt: z.date().optional(), // Auto-generated by Mongoose, can be optional in validation
  updatedAt: z.date().optional(), // Auto-generated by Mongoose, can be optional in validation
});

export type IOrderZod = z.infer<typeof orderZodSchema>;
